<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Email extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    public function sent_email($attachment, $name, $subject, $message) {
        $this->load->library('email');
        $this->email->from('purchasing.labparahita@gmail.com', 'Purchasing Lab Parahita');
        $this->email->to('muchtar.arekti@gmail.com');
        if ($subject != NULL) {
            $this->email->subject($subject);
        } else {
            $this->email->subject('Email Subject');
        }
        if ($message != NULL) {
            $this->email->message($message);
        } else {
            $this->email->message('This is email generated by software for Purchase Order.\n For Detail see PDF attachment');
        }
        if ($attachment != NULL) {
            $this->email->attach($attachment);
        }
        if ($this->email->send()) {
            return TRUE;
        } else {
            return $this->email->print_debugger();
        }
    }

    public function generate_pdf($file_path, $view, $data) {
        //boost the memory limit if it's low
        ini_set('memory_limit', '32M');
        //render the view into HTML
        $html = $this->load->view($view, $data);
        $this->load->library('pdf');
        $pdf = $this->pdf->load();
        // $pdf->SetFooter($_SERVER['HTTP_HOST'].'|{PAGENO}|'.date(DATE_RFC822));
        $pdf->WriteHTML($html); // write the HTML into the PDF
        $pdf->Output($file_path, 'F'); // D download, F file
        return;
    }

}
